---
# tasks file for roleservertools
- name: "Set hostname and update /etc/hosts when changed"
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify:
    - ClearHostsFile_loopback_localhost
    - ClearHostsFile_loopback_servername
    - ClearHostsFile_ip_servername
    - AddinHostsFile_loopback_localhost
    - AddinHostsFile_loopback_servername
    - AddinHostsFile_ip_servername
    - ClearAllEntries
    - UpdateAllEntries
    - Debug
