---
- name: ClearAllEntries
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    state: absent
  loop: "{{ groups['all'] }}"
  when: hostvars[item]['ansible_default_ipv4']['address'] is defined

- name: UpdateAllEntries
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['hostname'] }} "
    state: present
  loop: "{{ groups['all'] }}"
  when: hostvars[item]['ansible_default_ipv4']['address'] is defined

#
- name: Debug
  ansible.builtin.debug:
    msg: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['hostname'] }} "
  loop: "{{ groups['all'] }}"
  when: hostvars[item]['ansible_default_ipv4']['address'] is defined
