# tasks file for serverTools
- name: Task - Update Ubuntu packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3000

- name: Task - Upgrade Ubuntu packages
  ansible.builtin.apt:
    upgrade: true
    autoremove: true

- name: "Task - Install linux server tools"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3000
    name:
    - vim # text editor
    - ncdu # disk space
    - iotop # test - io
    - nmon # test - general
    - iftop # test - network
    - iperf # test - network
    - mtr # network throubleshooting
    - traceroute # network throubleshooting
    - stress # test - stress    | ex: stress --cpu 4 --timeout 60s
    - ntp # clock sync          | TODO task to config /etc/ntp.conf







