all:
  hosts:
  children:
    webservers:
      hosts:
        webserver1:
          hostname: "web01"
        webserver2:
          hostname: "web02"
    loadbalancers:
      hosts:
        LoadBalancer:
          hostname: "alb"
    databases:
      hosts:
        db:
          hostname: "db"
    sandboxes:
      hosts:
        sandbox:
          hostname: "sandbox"


