all:
  hosts:
  children:
    webservers:
      hosts:
        webserver1:
          hostname: "web01.local.com"
        webserver2:
          hostname: "web02.local.com"
    loadbalancers:
      hosts:
        LoadBalancer:
          hostname: "loadbalancer.local.com"
    databases:
      hosts:
        db:
          hostname: "database.local.com"
    sandboxes:
      hosts:
        sandbox:
          hostname: "sandbox.local.com"


