all:
  hosts:
  children:
    webservers:
      hosts:
        webserver1:
        webserver2:
    loadbalancers:
      hosts:
        LoadBalancer:
    databases:
      hosts:
        db:
    sandboxes:
      hosts:
        sandbox:

