all:
  hosts:
  children:
    webservers:
      hosts:
        webserver1:
          hostname: "w1.local.com"
        webserver2:
          hostname: "w2.local.com"
    loadbalancers:
      hosts:
        LoadBalancer:
          hostname: "lb.local.com"
    databases:
      hosts:
        db:
          hostname: "db.local.com"
    sandboxes:
      hosts:
        sandbox:
          hostname: "sandbox.local.com"


