---
# handlers file for roleservertools
- name: AddinHostsFile
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.0.1'
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 {{ hostname }}"
    - "{{ inventory_hostname }} {{ hostname }}"
