---
- hosts: all
  name: Update OS
  become: true

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        name: "*"
        state: present
