---
- name: Playbook - Update OS on all hosts
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Task - Update Ubuntu packages
      ansible.builtin.apt:
        update_cache: true
      when: ansible_hostname == "sandbox"
      # when: (ansible_facts['ansible_hostname'] == 'sandbox')

    - name: Task - Upgrade Ubuntu packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
      when: ansible_hostname == "sandbox"
