---
- name: Playbook - Update OS on all hosts
  hosts: sandbox
  become: true

  tasks:
    - name: Task - Update Ubuntu packages
      ansible.builtin.apt:
        update_cache: true

    - name: Task - Upgrade Ubuntu packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
